--- 
- 
  hosts: web-server
  name: server details
  tasks: 
    - 
      name: "remove httpd"
      yum: 
        name: httpd
        state: absent
    - 
      name: "install httpd server"
      service: 
        name: httpd
        state: present
